### ISSUE TITLE
Fixing a bug with SendConnectCommand function

### ISSUE THREAD

**Issue by ProbablyXS** [Bowhza/H2M-Launcher#12]
If the issue is that only "conect" is being written instead of "connect," it's possible that the command is being sent too quickly for the application to handle.

        private static void SendConnectCommand(string command)
        {
            IntPtr h2mModWindow = FindH2MModWindow();

            if (h2mModWindow != IntPtr.Zero)
            {
                //Open In Game Terminal Window
                SendMessage(h2mModWindow, WM_KEYDOWN, (IntPtr)Keys.Oemtilde, IntPtr.Zero);

                //Send the "connect" command to the terminal window
                foreach (char c in command)
                {
                    SendMessage(h2mModWindow, WM_CHAR, (IntPtr)c, IntPtr.Zero);
                    Thread.Sleep(1); // Slight delay to ensure all characters are processed
                }

                //Sleep for 1ms to allow the command to be processed
                Thread.Sleep(1);

                //Simulate pressing the Enter key
                SendMessage(h2mModWindow, WM_KEYDOWN, (IntPtr)Keys.Enter, IntPtr.Zero);
                SendMessage(h2mModWindow, WM_KEYUP, (IntPtr)Keys.Enter, IntPtr.Zero);

                SendMessage(h2mModWindow, WM_KEYDOWN, (IntPtr)Keys.Oemtilde, IntPtr.Zero);
            }
            else
            {
                MessageBox.Show("Could not find the h2m-mod terminal window.");
            }
        }

**Comment by Bowhza** [comment]
Has already been addressed in upcoming release.
